name: Unit Test

on:
  push: 
    branches: [ivanchen/unit-test]
  pull_request:
    branches:
      - main
      - dev
      - ga
      - hotfix/**/*

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ivanchen/unit-test
          repository: OfficeDev/TeamsFx

      - name: Merge Branches
        run: |
          git config --global user.email "ayachensiyuan@163.com"
          git config --global user.name "ayachensiyuan"

          git remote add OfficeDev https://github.com/OfficeDev/TeamsFx.git
          git fetch OfficeDev
          git merge OfficeDev/dev

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x

      - name: Setup project
        run: |
          npm run setup

      - name: Unit Test
        run: |
          xvfb-run -a npx lerna run test:unit --stream

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with: 
          token: 'b7ad5cf7-b01e-4383-a1d5-95f2dc9584b2'
          directory: './coverage'
